# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eddcd391f514bc3d60b31aae4ae925e8568e59c9eeeb0d126d3f111af130172706c3db4a8bc20b461714767fa6305b53697c9f9a266b6a94793995c2f52f2889

test:
  secret_key_base: 94e18a7c4f9050e4cf76c3f8fe1e7e4848d75a32237eba7240cc64d47f04517a13784ab9b90dc89009d062d557bf5dd21d3dbbce6e8e8e9f4360eb9fb4d3e4ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
